### ISSUE TITLE
Cannot find module nuxt-typo3-headless-news/Resources/Private/News/Templates/Vue/CeNews_pi1

### ISSUE THREAD

**Issue by donni106** [TYPO3-Initiatives/headless_news#10]
This error occurs when starting the nuxt server and visiting http://localhost:3000/:

<img width="1952" alt="Bildschirmfoto 2020-08-06 um 14 08 19" src="https://user-images.githubusercontent.com/1942953/89530179-58c95800-d7ee-11ea-85d2-3f8a436a37e9.png">

```javascript
/*
** Nuxt.js modules
*/
modules: [
  // Doc: https://github.com/TYPO3-Initiatives/headless_news
  'nuxt-typo3-headless-news',
  // Doc: https://github.com/TYPO3-Initiatives/nuxt-typo3
  'nuxt-typo3',
  '@nuxtjs/pwa',
  // Doc: https://github.com/nuxt-community/dotenv-module
  '@nuxtjs/dotenv'
],
```

Without `nuxt-typo3-headless-news` in the modules everything works fine.
Any idea?

**Comment by mercs600** [comment]
Did you add this package to frontend app ? ```yarn add nuxt-typo3-headless-news```

**Comment by donni106** [comment]
Yes

<img width="295" alt="Bildschirmfoto 2020-08-06 um 18 19 59" src="https://user-images.githubusercontent.com/1942953/89556310-752abc00-d811-11ea-8094-94001edd174c.png">

**Comment by donni106** [comment]
There is a `nuxt-typo3-headless-news` file in the `.nuxt` folder. In this file, the problematic code is included with the bad path. When I comment out everything, our app works.

```
// import Vue from "vue";
// import CeNews_pi1 from "nuxt-typo3-headless-news/Resources/Private/News/Templates/Vue/CeNews_pi1";
// export default () => {
//   Vue.component("CeNews_pi1", CeNews_pi1);
// };
```

Do I need that file/content? Or is this more like an example file, how to initially being able to use headless news?

**Comment by donni106** [comment]
With investing more, it seems like that our setup cannot find the `.vue` file in `nuxt-typo3-headless-news/Resources/Private/News/Templates/Vue/`. With trying to autocomplete the path, only `.js` files were proposed.

<img width="801" alt="Bildschirmfoto 2020-08-12 um 11 07 44" src="https://user-images.githubusercontent.com/1942953/89997168-11c6e100-dc8c-11ea-8fc8-f0c69b8d536d.png">

**Comment by donni106** [comment]
Wow, it seems to work, when adding `.vue` to the import from:

```
import Vue from "vue";
import CeNews_pi1 from "nuxt-typo3-headless-news/Resources/Private/News/Templates/Vue/CeNews_pi1.vue";
export default () => {
  Vue.component("CeNews_pi1", CeNews_pi1);
};
```

I will setup a PR for this!
