### ISSUE TITLE
Tags List template: /headless_news/Resources/Private/News/Templates/Tag/List.html

### ISSUE THREAD

**Issue by bk-damian-slomian** [TYPO3-Initiatives/headless_news#17]
The seo part is wrong. Should be:
```
<f:section name="TagsListView">
    <f:spaceless>
        <f:format.raw>
            <f:format.json value="{
              id: tagItem.uid,
              pid: tagItem.pid,
              title: tagItem.title,
              seo: {
                **seoTitle: tagItem.seoTitle,
                seoDescription: tagItem.seoDescription,
                seoHeadline: tagItem.seoHeadline,
                seoText: tagItem.seoText**
              },
              slug: '{f:uri.page(pageUid: settings.listPid, additionalParams: \'{tx_news_pi1: \\\'{overwriteDemand: \\\\\\\'{tags: tagItem.slug}\\\\\\\'}\\\'}\')}'
                }"/>
        </f:format.raw>
    </f:spaceless>
</f:section>
```

**Comment by bk-damian-slomian** [comment]
Same problem in: /headless_news/Resources/Private/News/Partials/Tags.html
<f:spaceless>
    [<f:for each="{tags}" as="tag" iteration="tagIterator">
        <f:format.raw>
            <f:format.json value="{
              id: tag.uid,
              pid: tag.pid,
              title: tag.title,
              seo: {
                **seoTitle: tag.seoTitle,
                seoDescription: tag.seoDescription,
                seoHeadline: tag.seoHeadline,
                seoText: tag.seo_text**
              },
              slug: tag.slug
            }"/>
        </f:format.raw>
        {f:if(condition: tagIterator.isLast, else: ',')}
    </f:for>]
</f:spaceless>

**Comment by tmotyl** [comment]
@bk-damian-slomian thanks for your feedback, can you send a Pull Request? Thanks

**Comment by bk-damian-slomian** [comment]
Done

**Comment by tmotyl** [comment]
thanks @bk-damian-slomian  and congratulations on your first contribution!
I'm closing the issue as it was fixed with https://github.com/TYPO3-Initiatives/headless_news/pull/18
